---
- name: Update APT package cache then install packages
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt: update_cache=yes cache_valid_time=7200
    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - htop
        - cmatrix